<a href="https://colab.research.google.com/github/Vivek-Sajjan/DS_Projects/blob/main/twitter_analysis_sprintcare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Sprintcare dataset-csv.csv')
display(df.head())

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [ ]:
df.shape

(11701, 7)

In [ ]:
# Create a new 'role' column based on the 'inbound' column
df['role'] = df['inbound'].apply(lambda x: 'Customer' if x else 'Service Provider')

# Get the list of existing columns
cols = df.columns.tolist()

# Move the 'role' column to the second position (index 2)
cols.insert(2, cols.pop(cols.index('role')))

# Reindex the DataFrame with the new column order
df = df[cols]

# Display the head of the modified DataFrame
display(df.head())

,tweet_id,author_id,role,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,Service Provider,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,Customer,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,Customer,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,Service Provider,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,Customer,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

# Task
Analyze the "Sprintcare dataset-csv.csv" file and build the conversations.

## Identify conversation starters

### Subtask:
Find the initial tweets that start a conversation (those with no `in_response_to_tweet_id`).

**Reasoning**:
Filter the dataframe to find tweets with no response, which signify the start of a conversation. Store the results in a new dataframe and display the head.

In [ ]:
conversation_starters_df = df[df['in_response_to_tweet_id'].isnull()]
display(conversation_starters_df.head())

,tweet_id,author_id,role,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
6,8,115712,Customer,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
22,1293,115712,Customer,True,Tue Oct 31 22:24:51 +0000 2017,@115714 @sprintcare how can I get in touch wit...,"1,29,11,29,61,297",NaN
39,3178,116445,Customer,True,Tue Oct 31 22:55:37 +0000 2017,@sprintcare mine and my brothers data is barel...,3176,NaN
52,5523,117001,Customer,True,Tue Oct 31 23:12:51 +0000 2017,@sprintcare @115714 thinking about upgrading m...,5522,NaN
58,7743,117302,Customer,True,Tue Oct 31 22:53:04 +0000 2017,@115714 @sprintcare &amp; she hung up the pho...,7742,NaN

In [ ]:
conversation_starters_df.shape

(917, 8)

## Trace conversations

### Subtask:
For the first few conversation starters, trace the subsequent tweets using `tweet_id`, `response_tweet_id`, and `in_response_to_tweet_id` to build complete conversation threads.

**Reasoning**:
Iterate through the all the conversation starters and trace their replies to build complete conversation threads.

In [ ]:
conversations = []
for index, starter_tweet in conversation_starters_df.iterrows():
    conversation = [starter_tweet]
    current_tweet_id = starter_tweet['tweet_id']

    while True:
        next_tweet = df[df['in_response_to_tweet_id'] == current_tweet_id]
        if not next_tweet.empty:
            # Assuming there's only one reply per tweet in a simple thread
            current_tweet = next_tweet.iloc[0]
            conversation.append(current_tweet)
            current_tweet_id = current_tweet['tweet_id']
        else:
            break
    conversations.append(conversation)

# Display the first conversation as an example
if conversations:
    print("First Conversation Thread:")
    for tweet in conversations[0]:
        display(tweet)

First Conversation Thread:

tweet_id                                                           8
author_id                                                     115712
role                                                        Customer
inbound                                                         True
created_at                            Tue Oct 31 21:45:10 +0000 2017
text                       @sprintcare is the worst customer service
response_tweet_id                                             9,6,10
in_response_to_tweet_id                                          NaN
Name: 6, dtype: object

tweet_id                                                                   6
author_id                                                         sprintcare
role                                                        Service Provider
inbound                                                                False
created_at                                    Tue Oct 31 21:46:24 +0000 2017
text                       @115712 Can you please send us a private messa...
response_tweet_id                                                        5,7
in_response_to_tweet_id                                                  8.0
Name: 5, dtype: object

tweet_id                                                5
author_id                                          115712
role                                             Customer
inbound                                              True
created_at                 Tue Oct 31 21:49:35 +0000 2017
text                                   @sprintcare I did.
response_tweet_id                                       4
in_response_to_tweet_id                               6.0
Name: 4, dtype: object

tweet_id                                                                   4
author_id                                                         sprintcare
role                                                        Service Provider
inbound                                                                False
created_at                                    Tue Oct 31 21:54:49 +0000 2017
text                       @115712 Please send us a Private Message so th...
response_tweet_id                                                          3
in_response_to_tweet_id                                                  5.0
Name: 3, dtype: object

tweet_id                                                                   3
author_id                                                             115712
role                                                                Customer
inbound                                                                 True
created_at                                    Tue Oct 31 22:08:27 +0000 2017
text                       @sprintcare I have sent several private messag...
response_tweet_id                                                          1
in_response_to_tweet_id                                                  4.0
Name: 2, dtype: object

tweet_id                                                                   1
author_id                                                         sprintcare
role                                                        Service Provider
inbound                                                                False
created_at                                    Tue Oct 31 22:10:47 +0000 2017
text                       @115712 I understand. I would like to assist y...
response_tweet_id                                                          2
in_response_to_tweet_id                                                  3.0
Name: 0, dtype: object

tweet_id                                                               2
author_id                                                         115712
role                                                            Customer
inbound                                                             True
created_at                                Tue Oct 31 22:11:45 +0000 2017
text                       @sprintcare and how do you propose we do that
response_tweet_id                                                    NaN
in_response_to_tweet_id                                              1.0
Name: 1, dtype: object

## Structure the conversations

### Subtask:
Organize the identified tweets into the distinct conversation structures.

**Reasoning**:
Create a list to store the structured conversations and iterate through the traced conversations to organize them into a structured format.

In [ ]:
import json
import numpy as np

# Custom encoder to handle NumPy types, including booleans
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

structured_conversations = []

for i, conversation_thread in enumerate(conversations):  # Process all conversations
    structured_thread = {
        'conversation_number': i + 1,
        'tweets': []
    }
    for tweet in conversation_thread:
        structured_thread['tweets'].append({
            'tweet_id': tweet['tweet_id'],
            'author_id': tweet['author_id'],
            'role': tweet['role'],
            'inbound': tweet['inbound'],
            'created_at': tweet['created_at'],
            'text': tweet['text']
        })
    structured_conversations.append(structured_thread)

# Display the first structured conversation as an example
if structured_conversations:
    print("First Structured Conversation:")
    # Print the dictionary representation for clarity
    print(json.dumps(structured_conversations[0], indent=4, cls=NpEncoder))

First Structured Conversation:
{
    "conversation_number": 1,
    "tweets": [
        {
            "tweet_id": 8,
            "author_id": "115712",
            "role": "Customer",
            "inbound": true,
            "created_at": "Tue Oct 31 21:45:10 +0000 2017",
            "text": "@sprintcare is the worst customer service"
        },
        {
            "tweet_id": 6,
            "author_id": "sprintcare",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "Tue Oct 31 21:46:24 +0000 2017",
            "text": "@115712 Can you please send us a private message, so that I can gain further details about your account?"
        },
        {
            "tweet_id": 5,
            "author_id": "115712",
            "role": "Customer",
            "inbound": true,
            "created_at": "Tue Oct 31 21:49:35 +0000 2017",
            "text": "@sprintcare I did."
        },
        {
            "tweet_id": 4,
            "author_id": "sprintcare",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "Tue Oct 31 21:54:49 +0000 2017",
            "text": "@115712 Please send us a Private Message so that we can further assist you. Just click \u2018Message\u2019 at the top of your profile."
        },
        {
            "tweet_id": 3,
            "author_id": "115712",
            "role": "Customer",
            "inbound": true,
            "created_at": "Tue Oct 31 22:08:27 +0000 2017",
            "text": "@sprintcare I have sent several private messages and no one is responding as usual"
        },
        {
            "tweet_id": 1,
            "author_id": "sprintcare",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "Tue Oct 31 22:10:47 +0000 2017",
            "text": "@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist."
        },
        {
            "tweet_id": 2,
            "author_id": "115712",
            "role": "Customer",
            "inbound": true,
            "created_at": "Tue Oct 31 22:11:45 +0000 2017",
            "text": "@sprintcare and how do you propose we do that"
        }
    ]
}

## Convert to JSON and Save

### Subtask:
Convert the structured conversations into a JSON format and save to a file.

**Reasoning**:
Use the `json` library to convert the `structured_conversations` list into a JSON formatted string and write it to a file.

In [ ]:
!pip install pytz

Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (2025.2)

In [ ]:
import json
import numpy as np
from datetime import datetime
import pytz

# Get current time in Indian Standard Time (IST)
ist = pytz.timezone('Asia/Kolkata')
current_time_ist = datetime.now(ist)

# Generate filename with current date and time (IST) in requested format
formatted_time = current_time_ist.strftime('%Y%m%d_%H%M%S')
output_filename = f'sprintcare_{formatted_time}.json'

# Custom encoder to handle NumPy types, including booleans
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

with open(output_filename, 'w') as f:
    json.dump(structured_conversations, f, indent=4, cls=NpEncoder)

print(f"Structured conversations saved to '{output_filename}'")

Structured conversations saved to 'sprintcare_20250916_104348.json'